const log = console.log;

document.addEventListener('DOMContentLoaded', init);

function init() {
    addListeners()
}

function addListeners() {
    const body = document.querySelector("body")
    body.addEventListener("click", bodyOrMain)
}

function bodyOrMain(ev) {
const oneOrZero = Math.round(Math.random())
if (oneOrZero === 1) {
    log("Setting a background colour to the body")
    // No need to do a reject because how could this ever fail, right?
    new Promise((resolve)=>{
        setTimeout(()=>{
            const bodyHexColor = randomColour();
            resolve(bodyHexColor);
        }, getRandomInt(1000, 2001));
    }).then((setBackground)=>{
        document.querySelector("body").style.backgroundColor = `${setBackground}`;
    })
} else {
    log("Adding <p> to main")
    new Promise ((resolve)=>{
        setTimeout(()=>{
            let p = document.createElement('p');
            p.innerText = conspiracyTheories();
            resolve(p)
        }, getRandomInt(1000, 2001));
    }).then((setP)=>{
        document.querySelector('main').append(setP);
    })
}
}

// Used for setting a timeout between one and two seconds. Am I reading this TOO literal from the instructions? Probably. Probably just needed to either put 1000 or 2000.
function getRandomInt(min, max) {
  const minCeiled = Math.ceil(min);
  const maxFloored = Math.floor(max);
  return Math.floor(Math.random() * (maxFloored - minCeiled) + minCeiled);
}

// Steve's random color creator from class.
function randomColour () {
    //return a random 6 digit hex colour
    return `#` + Math.random().toString(16).substring(2, 8);
}

// NOTE: Better practice would've been making this a JSON file and exporting it so I can call on it... but it's 11:39pm and I gotta get this in by 11:59pm
// There is just something fun about including something off the wall that an assignment doesn't really call on that I find hard to help. 

// The list of 10 were generated by AI with the prompt "Give me 10 real conspiracy theories, each in one sentence"

// This was initially me running getRandomInt(0, 11) and done a bunch of if else statements but that felt bad. 
function conspiracyTheories(conspiracies){
    const messages = [
        "Some people believe the Moon landing in 1969 was staged on a film set instead of actually happening on the Moon.",
        "A popular theory claims that chemtrails from airplanes are actually chemicals secretly sprayed to control the population or the weather.",
        "There’s a conspiracy theory that a secret group called the Illuminati secretly controls world events from behind the scenes.",
        "Some believe that 9/11 was an inside job orchestrated or allowed by elements within the U.S. government.",
        "A long-running theory claims that certain world leaders and celebrities are actually shape-shifting reptilian aliens.",
        "One conspiracy theory suggests that vaccines are part of a plot to track, control, or harm the population.",
        "Some people insist that powerful elites are hiding a cure for cancer to keep making money from treatments.",
        "There’s a theory that major tech companies and governments are using smartphones and smart devices to constantly spy on everyone.",
        "Some believe that the Earth is actually flat and that governments and scientists are hiding the truth.",
        "A conspiracy theory claims that major assassinations and 'lone wolf' attacks are often secretly coordinated by hidden organizations."
    ];
    const index = getRandomInt(0, messages.length);
    return messages[index];
}